email: "your-email@example.com"

# 证书配置列表
certificates:
  - domains: [ "example.com" ]
    dns_provider: "alidns"
    # 证书过期前多少天进行续期，默认 80 天
#    renew_before_expiry_days: 80
  - domains: [ "example.com" ]
    dns_provider: "alidns"
#    renew_before_expiry_days: 89
dns_provider_config:
  ALICLOUD_ACCESS_KEY: "LTAI4..."
  ALICLOUD_SECRET_KEY: "secret..."

apisix:
  admin_url: "http://apisix:9180"
  admin_key: "your-admin-token"

data_dir: "./data"
cron_schedule: "0 0 * * *"
lets_encrypt_env: "production"